### ISSUE TITLE
Still in 0.0.13 after upgrade to 0.1.0

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/owncast_ynh#39] opened 2023-05-30 20:40 UTC
# My config
Yunohost 11.1.20 (stable)
VPS Hetzner CX 31 (8Go RAM 2 vCPU intel)
Interface admin + SSH

# The problem
I'm still in 0.0.13 after upgrade.
Here are the logs : https://paste.yunohost.org/bapovozuci

**Comment by ericgaspar** [comment] 2023-06-05 20:21
I am not really sure how to solve the probleme here... 0.1.0 seems to be à big update with file structure changes. Do you still have the `webroot` folder still present in `/var/www/owncast`? what about removing it and restart the service?

**Comment by taintedcypher** [comment] 2023-06-07 18:12
hi @ericgaspar, I moved the owncast/webroot folder away and restarted the service. The service restarts, and it looks like the admin interface works, and it seems it's listening for rtmp.
But, the main user interface is blank, the webroot folder is still missing.

Plus, the /api/status json still says  `"versionNumber":"0.0.13"`

**Comment by filippodb** [comment] 2023-06-17 23:55
I have the same problem:

https://paste.yunohost.org/raw/jicuwomedi

**Comment by BishopGreer** [comment] 2023-06-30 22:24
Any roadmap to fixing this? I too have this issue.

**Comment by ericgaspar** [comment] 2023-07-01 07:25
Reinstalling the app should fix the issue.

**Comment by Szkodnix** [comment] 2023-07-03 17:08
So, as I understand, you would like us to reinstall the app completely and start from the scratch?

There is really no other way to update the software without sacrificing our configuration and customization?

**Comment by ericgaspar** [comment] 2023-07-03 17:10
or you can wait for the issue to be solved, which can take some time...

**Comment by Szkodnix** [comment] 2023-07-03 17:19
> or you can wait for the issue to be solved, which can take some time...

Fair enough! Take as much time as you need! :)

**Comment by BishopGreer** [comment] 2023-07-11 15:49
I can confirm that removing and reinstalling fixes the issue. The upgrade from 0.0.13 to 0.1.0 does not actually upgrade. Hope that info helps.

**Comment by Szkodnix** [comment] 2023-07-11 20:49
> I can confirm that removing and reinstalling fixes the issue. The upgrade from 0.0.13 to 0.1.0 does not actually upgrade. Hope that info helps.

Thanks for checking. Still, I will probably wait for some actual fix not to lose my configuration.

**Comment by ericgaspar** [comment] 2023-07-11 20:59
To be honest, I don't know if this issue will be fixed without the upgrade script removing and reinstalling the app. Since we don't have a configuration file to save for this app, it will be the same as deleting and reinstalling OwnCast.

**Comment by taintedcypher** [comment] 2023-07-12 19:42
From what I've seen, I believe all of the settings are in the *owncast.db* sqlite file, which is in the data folder.
I just took that folder from my 0.0.13 ynh install and fed it to a 0.1.0 container image, and I found all my settings back!
Maybe the update script can do something similar after having reinstalled the app?

**Closed** 2023-07-13 04:34 UTC
